server:
  port: 8086
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/trysql?useUnicode=true&characterEncoding=utf8
    username: root
    password: 965362
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    mode: HTML5
  resources:
    static-locations: classpath:/static/

  jpa:
    database: mysql
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.qf.pojo
qiniu:
  accessKey: xJX1qRamYYsrkYHKtD9YLGaFWIIQcNsmnYjuVKt_
  secretKey: REXGlqKFd6OUw8ot97WbNYFJII2scs-HJ9087jNz
  bucket: licong188
  url: http://q1cw3v594.bkt.clouddn.com/
